### ISSUE TITLE
Where to download libvlc.dll and libvlcCore.dll?

### ISSUE THREAD

**Issue by chonghai** [HemulGM/VLC#1]
Where to download libvlc.dll and libvlcCore.dll?
thks!

**Comment by chonghai** [comment]
I download the VideoLAN, and the DLLs are in that. Copy is OK.

**Comment by HemulGM** [comment]
I recommend downloading the VCL player, installing and copying almost all contents, except for the executable files.
You can download the embedded version to avoid installing.

**Comment by chonghai** [comment]
> 
> 
> I recommend downloading the VCL player, installing and copying almost all contents, except for the executable files.
> You can download the embedded version to avoid installing.

thanks! but when I use Delphi 10.4.1 to compile the project , many compiling error are found.
Have you any suggestion for that?

**Comment by HemulGM** [comment]
What kind of error?

**Comment by chonghai** [comment]
> 
> 
> What kind of error?

just like that:
[dcc32 Error] FmxPasLibVlcPlayerUnit.pas(3635): E2003 Undeclared identifier: 'lock'

that define:
TVideoCbCtx = record
    {$IFDEF HAS_SYNCOBJS}
    lock        : TCriticalSection;
    {$ENDIF}

**Comment by chonghai** [comment]
> 
> 
> What kind of error?

Which version of Delphi do you use to compile the program? thks!

**Comment by HemulGM** [comment]
I'm use RAD Studio 10.3.3 (CE)

**Comment by DeveloppeurPascal** [comment]
Hi @chonghai, no problem for me with 10.4.1 release of Delphi. Did you changed something from the repository ? Can you give me last part of your Delphi version number ? (help / about box)

**Comment by HemulGM** [comment]
I'm use RAD Studio 10.3.3 (CE)
